### ISSUE TITLE
Modify num_worker to 1, 2 or other number,  RuntimeError: unable to mmap 32 bytes from file </torch_239305_1669300387>: Cannot allocate memory (12)

### ISSUE THREAD

**Issue by hustpenghuan** [bbepoch/HoiTransformer#22]
Traceback (most recent call last):                                                                                               
  File "slurm_main.py", line 243, in <module>
    main(args)                     
  File "slurm_main.py", line 200, in main                                                                                     
    args.clip_max_norm)                     
  File "/mnt/lustre/penghuan/HoiTransformer/engine.py", line 32, in train_one_epoch                                                   for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/mnt/lustre/penghuan/HoiTransformer/util/misc.py", line 223, in log_every
    for obj in iterable:                                                                               
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line
 355, in __iter__                  
    return self._get_iterator()                                                           
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line
 301, in _get_iterator                                            
    return _MultiProcessingDataLoaderIter(self)                           
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line
 914, in __init__                                                        
    w.start()                                                     
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)                                
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/multiprocessing/context.py", line 223, in _Popen       return _default_context.get_context().Process._Popen(process_obj)        
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj) 
 File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/r1024/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to mmap 32 bytes from file </torch_239305_1669300387>: Cannot allocate memory (12)

**Comment by bbepoch** [comment]
Setting num_worker=0 is enough, because the time of feeding data in each iteration is less than 20%.
